source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'pg'

gem 'superslug'

group :development do
  gem 'guard-rspec', :require => false
  gem 'annotate'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
end
